### ISSUE TITLE
Issue in scripts/AlignBandColors: Fits without 'CD1_2' in header will crash program

### ISSUE THREAD

**Issue by cora-schallock** [waynebhayes/SpArcFiRe#63]
Error Message:
```Traceback (most recent call last):
  File "./shift_gal.py", line 435, in <module>
    process_galaxy(gal, args.outDir, args.borderSize, args.minStarsTemplate, args.minStarsAll, args.upscaleFactor, ar                                                                                                                        gs.cropImages, args.runInParallel, args.maxMemory * 1024**3, args.compressOutput)
  File "./shift_gal.py", line 316, in process_galaxy
    save_output(p, galaxy, shift_imgs, shift_vectors, compressOutput)
  File "./shift_gal.py", line 250, in save_output
    hdu[0].header['CRVAL1'] += (shift_vectors[color][1] - int(shift_vectors[color][1])) * hdu[0].header['CD1_2']
  File "/home/whayes/.local/lib/python2.7/site-packages/astropy/io/fits/header.py", line 150, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "/home/whayes/.local/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1677, in _cardindex
    raise KeyError("Keyword {!r} not found.".format(keyword))
KeyError: "Keyword 'CD1_2' not found."
```

Temporary Workaround:
In `shift_gal.py`  comment out lines that write to header of shifted_galaxy fits

Steps to Recreate Error:
1) Download [ngc615](https://ps1images.stsci.edu/cgi-bin/ps1cutouts?pos=NGC615&filter=color&filter=g&filter=r&filter=i&filter=z&filter=y&filetypes=stack&auxiliary=data&auxiliary=mask&size=600&output_size=256&verbose=0&autoscale=99.500000&catlis0t=
)
2) rename y band to u (for workaround of other issue)
3) ./runShiftGal.sh inDir/ outDir/

**Comment by cora-schallock** [comment]
Issue fixed with recent merge: https://github.com/waynebhayes/SpArcFiRe/pull/67
