### ISSUE TITLE
Issue in scripts/AlignBandColors: Galaxies without same color bands as SDSS will not work

### ISSUE THREAD

**Issue by cora-schallock** [waynebhayes/SpArcFiRe#64]
Issue with using wavebands not present in SDSS, for example the [y band](https://panstarrs.stsci.edu/) in the Pan-STARRS1 survey

Error:
```
Traceback (most recent call last):
  File "./shift_gal.py", line 436, in <module>
    process_galaxy(gal, args.outDir, args.borderSize, args.minStarsTemplate, args.minStarsAll, args.upscaleFactor, args.cropImages, args.runInParallel, args.maxMemory * 1024**3, args.compressOutput)
  File "./shift_gal.py", line 320, in process_galaxy
    print_vec(shift_vectors['g']), print_vec(shift_vectors['i']), print_vec(shift_vectors['r']), print_vec(shift_vectors['u']), print_vec(shift_vectors['z']),
KeyError: 'u'
```

Temporary Workaround:
rename fits that have a filter not in SDSS to an SDSS
ex: mv ngc615_y.fits ngc615_u.fits #rename y band to u band

Steps to Recreate Error:
1) Download [ngc615](https://ps1images.stsci.edu/cgi-bin/ps1cutouts?pos=NGC615&filter=color&filter=g&filter=r&filter=i&filter=z&filter=y&filetypes=stack&auxiliary=data&auxiliary=mask&size=600&output_size=256&verbose=0&autoscale=99.500000&catlis0t=
)
2) ./runShiftGal.sh inDir/ outDir/

**Comment by cora-schallock** [comment]
Also this maybe a potential issue if you want to run AlignBandColor with only four bands.

I'm not sure if that would be something worthwhile to support, but there are some galaxies where I could imagine it would be easier to ignore one band with bad visual artifacts and use remaining 4 bands to align.
For example, [NGC1097](https://ps1images.stsci.edu/cgi-bin/ps1cutouts?pos=NGC1097&filter=color&filter=g&filter=r&filter=i&filter=z&filter=y&filetypes=stack&auxiliary=data&auxiliary=mask&size=1000&output_size=256&verbose=0&autoscale=99.500000&catlist=) g-band is pretty messed up but other bands look fine.

**Comment by cora-schallock** [comment]
Issue fixed with recent merge: https://github.com/waynebhayes/SpArcFiRe/pull/67
